on: [push, pull_request, workflow_dispatch]

name: Build

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: zmkfirmware/zmk-build-arm:stable
    name: Build
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Cache west modules
        uses: actions/cache@v4
        env:
          cache-name: cache-zephyr-modules
        with:
          path: |
            modules/
            tools/
            zephyr/
            bootloader/
            zmk/
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('manifest-dir/west.yml') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: West Init
        run: west init -l config
      - name: West Update
        run: west update
      - name: West Zephyr export
        run: west zephyr-export
      - name: Copy common keymap to Andrea folders
        run: cp ${GITHUB_WORKSPACE}/andrea.keymap ${GITHUB_WORKSPACE}/config/boards/arm/andrea/andrea.keymap && cp ${GITHUB_WORKSPACE}/andrea.keymap ${GITHUB_WORKSPACE}/config/boards/arm/andrea_rev2/andrea_rev2.keymap
      - name: West Build (Andrea)
        run: west build -s zmk/app -b andrea -- -DZMK_CONFIG="${GITHUB_WORKSPACE}/config"
      - name: Andrea Kconfig file
        run: cat build/zephyr/.config | grep -v "^#" | grep -v "^$"
      - name: Rename zmk.uf2
        run: cp build/zephyr/zmk.uf2 Andrea-31-Mar-2021-Firmware.uf2
      - name: Archive (Andrea)
        uses: actions/upload-artifact@v4
        with:
          name: andrea_31-mar-2021
          path: Andrea-31-Mar-2021-Firmware.uf2
      - name: West Build (Andrea Rev2)
        run: west build -s zmk/app -b andrea_rev2 --pristine -- -DZMK_CONFIG="${GITHUB_WORKSPACE}/config"
      - name: Andrea Rev 2 Kconfig file
        run: cat build/zephyr/.config | grep -v "^#" | grep -v "^$"
      - name: Rename zmk.uf2
        run: cp build/zephyr/zmk.uf2 Andrea-14-Apr-2021-Firmware.uf2
      - name: Archive (Andrea Rev 2)
        uses: actions/upload-artifact@v4
        with:
          name: andrea_14-apr-2021
          path: Andrea-14-Apr-2021-Firmware.uf2
